In [1]:
from google.colab import drive
import os
import pandas as pd
from sklearn.model_selection import train_test_split

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Copying to Colabs local SSD
!cp -r "/content/drive/MyDrive/MMRetrieval/flickr8k" /content/

In [3]:
#DATASET_DIR = "/content/drive/MyDrive/MMRetrieval/flickr8k"
IMAGE_DIR = "/content/flickr8k/Images"
CAPTION_FILE = "/content/flickr8k/captions.txt"

In [4]:
print("Images:", len(os.listdir(IMAGE_DIR)))

df = pd.read_csv(CAPTION_FILE)

print(df.head())
print(df.columns)
print(df.shape)

Images: 8091
                       image  \
0  1000268201_693b08cb0e.jpg
1  1000268201_693b08cb0e.jpg
2  1000268201_693b08cb0e.jpg
3  1000268201_693b08cb0e.jpg
4  1000268201_693b08cb0e.jpg

                                             caption
0  A child in a pink dress is climbing up a set o...
1              A girl going into a wooden building .
2   A little girl climbing into a wooden playhouse .
3  A little girl climbing the stairs to her playh...
4  A little girl in a pink dress going into a woo...
Index(['image', 'caption'], dtype='object')
(40455, 2)

In [5]:
images = df["image"].unique().tolist()

print("Unique images:", len(images))

Unique images: 8091

In [6]:
# Create fixed split, 80, 10, 10
train_imgs, temp_imgs = train_test_split(
    images,
    train_size=6000,
    random_state=42,
    shuffle=True
)

val_imgs, test_imgs = train_test_split(
    temp_imgs,
    test_size=1000,
    random_state=42,
    shuffle=True
)

print(len(train_imgs))
print(len(val_imgs))
print(len(test_imgs))

6000
1091
1000

In [7]:
# Train test and val dataset
train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)

val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)

test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

In [8]:
# Save files in drive
import pickle

split_dict = {
    "train": train_imgs,
    "val": val_imgs,
    "test": test_imgs
}

with open(
    "/content/flickr8k/flickr8k_split.pkl",
    "wb"
) as f:
    pickle.dump(split_dict, f)

In [9]:
# Test Load
with open(
    "/content/flickr8k/flickr8k_split.pkl",
    "rb"
) as f:
    split_dict = pickle.load(f)

In [10]:
train_df.head()

,image,caption
0,1001773457_577c3a7d70.jpg,A black dog and a spotted dog are fighting
1,1001773457_577c3a7d70.jpg,A black dog and a tri-colored dog playing with...
2,1001773457_577c3a7d70.jpg,A black dog and a white dog with brown spots a...
3,1001773457_577c3a7d70.jpg,Two dogs of different breeds looking at each o...
4,1001773457_577c3a7d70.jpg,Two dogs on pavement moving toward each other .

Data Preprocessing

In [11]:
import re
from collections import Counter
import pickle

In [12]:
# Clean captions

def clean_caption(text):
    text = text.lower()

    # remove punctuation
    text = re.sub(r"[^a-z0-9\s]", "", text)

    # collapse spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [13]:
# Apply on the datasets

train_df["caption"] = train_df["caption"].apply(clean_caption)
val_df["caption"] = val_df["caption"].apply(clean_caption)
test_df["caption"] = test_df["caption"].apply(clean_caption)

In [14]:
# Add the specialised tokens

PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"
SOS_TOKEN = "<SOS>"
EOS_TOKEN = "<EOS>"

In [15]:
# Train data vocab

counter = Counter()

for caption in train_df["caption"]:
    counter.update(caption.split())

In [16]:
print("Unique words:", len(counter))

Unique words: 7744

In [17]:
# Create Vocab

MIN_FREQ = 5

vocab = {
    PAD_TOKEN: 0,
    UNK_TOKEN: 1,
    SOS_TOKEN: 2,
    EOS_TOKEN: 3
}

for word, freq in counter.items():
    if freq >= MIN_FREQ:
        vocab[word] = len(vocab)

idx2word = {idx: word for word, idx in vocab.items()}

In [18]:
print("Vocabulary size:", len(vocab))

Vocabulary size: 2561

In [19]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [20]:
# Set Max caption length for batching

lengths = []

for caption in train_df["caption"]:
    lengths.append(
        len(caption.split()) + 2
    )

print("Max length:", max(lengths))
print("Average length:", sum(lengths)/len(lengths))

Max length: 38
Average length: 12.790533333333334

In [21]:
MAX_LEN = 38

In [22]:
# Save and reload vocab

with open(
    "/content/flickr8k/vocab.pkl",
    "wb"
) as f:
    pickle.dump(vocab, f)

In [23]:
with open(
    "/content/flickr8k/vocab.pkl",
    "rb"
) as f:
    vocab = pickle.load(f)

Dataset Classes

In [24]:
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image
import os
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader

In [25]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [26]:
from collections import defaultdict
import random

train_caption_map = defaultdict(list)
val_caption_map = defaultdict(list)
test_caption_map = defaultdict(list)

bad_img = "861608773_bdafd5c996.jpg"

train_caption_map.pop(bad_img, None)
val_caption_map.pop(bad_img, None)
test_caption_map.pop(bad_img, None)

for _, row in train_df.iterrows():
    train_caption_map[row["image"]].append(row["caption"])

for _, row in val_df.iterrows():
    val_caption_map[row["image"]].append(row["caption"])

for _, row in test_df.iterrows():
    test_caption_map[row["image"]].append(row["caption"])


class Flickr8KRetrievalDataset(Dataset):
    def __init__(self, caption_map, image_dir, vocab, transform=None, random_caption=True):
        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):
        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]      # fixed caption for eval

        try:
          image = Image.open(
              os.path.join(self.image_dir, image_name)
          ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [27]:
class Flickr8KAllCaptionEvalDataset(Dataset):

    def __init__(self, caption_map, image_dir, vocab, transform=None):

        self.samples = []
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform

        for image_name in sorted(caption_map.keys()):

            for caption in caption_map[image_name]:

                self.samples.append(
                    (image_name, caption)
                )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        image_name, caption = self.samples[idx]

        image = Image.open(
            os.path.join(self.image_dir, image_name)
        ).convert("RGB")

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, torch.tensor(caption)

In [93]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    captions = []
    lengths = []

    for image, caption in batch:
        images.append(image)
        captions.append(caption)
        lengths.append(len(caption))

    images = torch.stack(images)

    captions = pad_sequence(
        captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    lengths = torch.tensor(lengths)

    return images, captions, lengths

In [94]:
train_dataset = Flickr8KRetrievalDataset(
    train_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=True
)

val_dataset = Flickr8KRetrievalDataset(
    val_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=False
)

test_dataset = Flickr8KRetrievalDataset(
    test_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=False
)

In [95]:
all_caption_test_dataset = Flickr8KAllCaptionEvalDataset(
    test_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform
)

In [96]:
print(len(train_dataset))
print(len(val_dataset))
print(len(test_dataset))

6000
1091
1000

In [97]:
# Dataloaders for clip style loading
BATCH_SIZE = 256

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)

In [98]:
all_caption_test_loader = DataLoader(
    all_caption_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=0
)

In [99]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [100]:
device

'cuda'

In [101]:
print("device" in globals())
print("text_encoder" in globals())
print("train_loader" in globals())

True
True
True

In [102]:
image, caption = train_dataset[0]

print(image.shape)

print(caption)

torch.Size([3, 224, 224])
tensor([ 2, 26, 27, 28, 29, 30, 31, 23, 14, 15, 16, 17, 18,  3])

ViT(vit_base_patch16_224) Image Encoder

In [103]:
EMBED_DIM = 256

In [104]:
import timm
import torch
import torch.nn as nn
import torch.nn.functional as F

class ViTEncoder(nn.Module):

    def __init__(self, freeze=True):
        super().__init__()
        self.freeze = freeze # Store freeze as an instance attribute

        # Original ViT-B/16 (Dosovitskiy et al., 2020)
        self.vit = timm.create_model(
            "vit_base_patch16_224",
            pretrained=True,
            num_classes=0
        )

        # Freeze ViT initially
        if self.freeze:
            for param in self.vit.parameters():
                param.requires_grad = False

        # Projection Head
        self.projection = nn.Sequential(
            nn.Linear(768, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, 512)
        )

    def forward(self, images):

        # ViT Features
        if self.freeze:
            with torch.no_grad():
                features = self.vit(images)
        else:
            features = self.vit(images)

        # Projection
        embeddings = self.projection(features)   # (B,512)

        # Normalize
        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

Replace the entire LSTM encoder with a Transformer Encoder while keeping the output as a 512-dimensional embedding so that it remains compatible with existing ViT encoder and Bidirectional InfoNCE loss.

In [105]:
# Text Encoder (Transformer Encoder)

import math
import torch
import torch.nn as nn
import torch.nn.functional as F


class PositionalEncoding(nn.Module):
    def __init__(self, embed_dim, max_len=5000):
        super().__init__()

        pe = torch.zeros(max_len, embed_dim)
        position = torch.arange(0, max_len).unsqueeze(1).float()

        div_term = torch.exp(
            torch.arange(0, embed_dim, 2).float()
            * (-math.log(10000.0) / embed_dim)
        )

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)      # (1, max_len, embed_dim)

        self.register_buffer("pe", pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]


class TextEncoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=512,
        num_heads=8,
        num_layers=4,
        ff_dim=2048,
        pad_idx=0,
        dropout=0.1
    ):
        super().__init__()

        # Word Embedding
        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        # Positional Encoding
        self.position = PositionalEncoding(embed_dim)

        # Transformer Encoder Layer
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=ff_dim,
            dropout=dropout,
            activation="gelu",
            batch_first=True
        )

        # Transformer Encoder
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        # Projection Head
        self.projection = nn.Sequential(
            nn.Linear(embed_dim, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, 512)
        )

    def forward(
        self,
        captions,
        lengths
    ):

        # Word Embeddings
        x = self.embedding(captions)

        # Positional Encoding
        x = self.position(x)

        # Padding Mask
        device = captions.device

        max_len = captions.size(1)

        lengths = lengths.to(device)

        mask = (
            torch.arange(max_len, device=device)
            .expand(len(lengths), max_len)
            >= lengths.unsqueeze(1)
        )

        # Transformer Encoder
        x = self.transformer(
            x,
            src_key_padding_mask=mask
        )

        # Mean Pooling (ignore padding)
        mask_float = (~mask).unsqueeze(-1).float()

        x = (x * mask_float).sum(dim=1) / mask_float.sum(dim=1)

        # Projection
        embeddings = self.projection(x)

        # Normalize
        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [106]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

In [107]:
encoder = ViTEncoder().to(device)

images, captions, lengths = next(iter(train_loader))

images = images.to(device)

with torch.no_grad():
    image_embeddings = encoder(images)

print(image_embeddings.shape)

torch.Size([256, 512])

In [108]:
# text encoder installation and test
text_encoder = TextEncoder(
    vocab_size=len(vocab),
    embed_dim=512,
    num_heads=8,
    num_layers=4,
    ff_dim=2048,
    pad_idx=vocab["<PAD>"],
    dropout=0.1
).to(device)

images, captions, lengths = next(iter(train_loader))

captions = captions.to(device)

with torch.no_grad():
    text_embeddings = text_encoder(
        captions,
        lengths
    )

print(text_embeddings.shape)

torch.Size([256, 512])

In [109]:
# compatibility verification
with torch.no_grad():
    image_embeddings = encoder(images.to(device))

    text_embeddings = text_encoder(
        captions.to(device),
        lengths
    )

print(image_embeddings.shape)
print(text_embeddings.shape)

torch.Size([256, 512])
torch.Size([256, 512])

In [110]:
# Normalize embedding
import torch.nn.functional as F

image_embeddings = F.normalize(image_embeddings, dim=1)
text_embeddings = F.normalize(text_embeddings, dim=1)

print(image_embeddings.norm(dim=1).mean())
print(text_embeddings.norm(dim=1).mean())

tensor(1., device='cuda:0')
tensor(1., device='cuda:0')

In [111]:
# Joint Model (ViT + Transformer Retrieval)

import torch
import torch.nn as nn
import numpy as np

class ViTTransformerRetrieval(nn.Module):

    def __init__(self, image_encoder, text_encoder):
        super().__init__()

        self.image_encoder = image_encoder
        self.text_encoder = text_encoder

        # Learnable temperature parameter (CLIP-style)
        self.logit_scale = nn.Parameter(
            torch.ones([]) * np.log(1 / 0.07)
        )

    def forward(self, images, captions, lengths):

        # Image embeddings from ViT
        image_emb = self.image_encoder(images)

        # Caption embeddings from Transformer Encoder
        text_emb = self.text_encoder(captions, lengths)

        return image_emb, text_emb


# Build Model
model = ViTTransformerRetrieval(
    image_encoder=encoder,
    text_encoder=text_encoder
).to(device)

In [112]:
# CLIP-Style Contrastive Loss

def clip_contrastive_loss(image_emb, text_emb, logit_scale):

    # CLIP-style learnable temperature
    logit_scale = logit_scale.exp().clamp(max=100)

    # Similarity Matrix
    logits = torch.matmul(image_emb, text_emb.T) * logit_scale

    # Ground truth labels
    targets = torch.arange(
        image_emb.size(0),
        device=image_emb.device
    )

    # Image → Text
    loss_i2t = F.cross_entropy(logits, targets)

    # Text → Image
    loss_t2i = F.cross_entropy(logits.T, targets)

    # Bidirectional InfoNCE
    loss = (loss_i2t + loss_t2i) / 2

    return loss, logits

In [113]:
# Forward pass test
images, captions, lengths = next(iter(train_loader))

images = images.to(device)
captions = captions.to(device)

with torch.no_grad():
    image_emb, text_emb = model(
        images,
        captions,
        lengths
    )

print(image_emb.shape)
print(text_emb.shape)

torch.Size([256, 512])
torch.Size([256, 512])

In [114]:
# Loss test
loss, logits = clip_contrastive_loss(
    image_emb,
    text_emb,
    model.logit_scale
)

print(loss.item())
print(logits.shape)

5.680750846862793
torch.Size([256, 256])

In [115]:
# Training
optimizer = torch.optim.AdamW(
    [
        {
            "params": model.image_encoder.vit.parameters(),
            "lr": 1e-5
        },
        {
            "params": model.image_encoder.projection.parameters(),
            "lr": 3e-4
        },
        {
            "params": model.text_encoder.parameters(),
            "lr": 3e-4
        },
        {
            "params": [model.logit_scale],
            "lr": 1e-4
        }
    ],
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=50
)

In [116]:
# Add Validation Loop
def evaluate(model, dataloader, device):
    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            image_emb, text_emb = model(
                images,
                captions,
                lengths
            )

            loss, _ = clip_contrastive_loss(
                image_emb,
                text_emb,
                model.logit_scale
            )

            total_loss += loss.item()

    return total_loss / len(dataloader)

In [117]:
import gc
import torch

gc.collect()
torch.cuda.empty_cache()
del images, captions
gc.collect()
torch.cuda.empty_cache()

In [118]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA A100-SXM4-80GB

In [119]:
print(len(train_loader))

24

In [120]:
print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))

Train batches: 24
Validation batches: 5

In [121]:
print(train_dataset.image_dir)

/content/flickr8k/Images

In [122]:
import time
import torch

# Training
NUM_EPOCHS = 50
best_val_loss = float("inf")

BEST_MODEL_PATH = "/content/drive/MyDrive/MMRetrieval/ViT_Transformer_m1/best_retrieval_ViTTransformer_model.pth"

for epoch in range(NUM_EPOCHS):

    print(f"\n================ Epoch {epoch+1}/{NUM_EPOCHS} ================")

    model.train()
    running_loss = 0.0

    epoch_start = time.time()

    for batch_idx, (images, captions, lengths) in enumerate(train_loader):

        batch_start = time.time()

        images = images.to(device, non_blocking=True)
        captions = captions.to(device, non_blocking=True)

        optimizer.zero_grad()

        image_emb, text_emb = model(
            images,
            captions,
            lengths
        )

        loss, _ = clip_contrastive_loss(
            image_emb,
            text_emb,
            model.logit_scale
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=1.0
        )

        optimizer.step()

        running_loss += loss.item()

        batch_time = time.time() - batch_start

        print(
            f"Batch {batch_idx+1:02d}/{len(train_loader)} | "
            f"Loss: {loss.item():.4f} | "
            f"Time: {batch_time:.2f}s"
        )

    train_time = time.time() - epoch_start

    train_loss = running_loss / len(train_loader)

    # ---------------- Validation ----------------
    val_start = time.time()

    val_loss = evaluate(
        model,
        val_loader,
        device
    )

    val_time = time.time() - val_start

    scheduler.step()

    print("\n---------------- Summary ----------------")
    print(f"Train Loss     : {train_loss:.4f}")
    print(f"Validation Loss: {val_loss:.4f}")
    print(f"Training Time  : {train_time:.2f} sec")
    print(f"Validation Time: {val_time:.2f} sec")
    print(
        f"GPU Memory Used: "
        f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
    )

    # Save best model
    if val_loss < best_val_loss:

        best_val_loss = val_loss

        torch.save(
            {
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "epoch": epoch,
                "val_loss": val_loss
            },
            BEST_MODEL_PATH
        )

        print("✓ Best model saved")

================ Epoch 1/50 ================
Batch 01/24 | Loss: 5.6817 | Time: 0.58s
Batch 02/24 | Loss: 5.5937 | Time: 0.56s
Batch 03/24 | Loss: 5.5767 | Time: 0.56s
Batch 04/24 | Loss: 5.5777 | Time: 0.55s
Batch 05/24 | Loss: 5.5438 | Time: 0.56s
Batch 06/24 | Loss: 5.5182 | Time: 0.56s
Batch 07/24 | Loss: 5.4804 | Time: 0.56s
Batch 08/24 | Loss: 5.3299 | Time: 0.56s
Batch 09/24 | Loss: 5.2639 | Time: 0.55s
Batch 10/24 | Loss: 5.1471 | Time: 0.56s
Batch 11/24 | Loss: 5.1916 | Time: 0.55s
Batch 12/24 | Loss: 5.1738 | Time: 0.56s
Batch 13/24 | Loss: 5.0440 | Time: 0.56s
Batch 14/24 | Loss: 4.9941 | Time: 0.55s
Batch 15/24 | Loss: 4.8726 | Time: 0.56s
Batch 16/24 | Loss: 4.8243 | Time: 0.56s
Batch 17/24 | Loss: 4.8547 | Time: 0.56s
Batch 18/24 | Loss: 4.8274 | Time: 0.55s
Batch 19/24 | Loss: 4.8069 | Time: 0.56s
Batch 20/24 | Loss: 4.8147 | Time: 0.56s
Batch 21/24 | Loss: 4.7495 | Time: 0.56s
Batch 22/24 | Loss: 4.7129 | Time: 0.56s
Batch 23/24 | Loss: 4.5732 | Time: 0.56s
Batch 24/24 | Loss: 3.9458 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 5.0874
Validation Loss: 4.2803
Training Time  : 19.92 sec
Validation Time: 4.49 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 2/50 ================
Batch 01/24 | Loss: 4.5461 | Time: 0.58s
Batch 02/24 | Loss: 4.4129 | Time: 0.55s
Batch 03/24 | Loss: 4.3579 | Time: 0.56s
Batch 04/24 | Loss: 4.2960 | Time: 0.56s
Batch 05/24 | Loss: 4.3184 | Time: 0.56s
Batch 06/24 | Loss: 4.2827 | Time: 0.56s
Batch 07/24 | Loss: 4.1985 | Time: 0.56s
Batch 08/24 | Loss: 4.2684 | Time: 0.56s
Batch 09/24 | Loss: 4.2379 | Time: 0.56s
Batch 10/24 | Loss: 4.1801 | Time: 0.56s
Batch 11/24 | Loss: 4.1296 | Time: 0.56s
Batch 12/24 | Loss: 4.0434 | Time: 0.56s
Batch 13/24 | Loss: 3.9941 | Time: 0.56s
Batch 14/24 | Loss: 3.9790 | Time: 0.56s
Batch 15/24 | Loss: 3.8604 | Time: 0.55s
Batch 16/24 | Loss: 3.9205 | Time: 0.56s
Batch 17/24 | Loss: 3.8808 | Time: 0.56s
Batch 18/24 | Loss: 3.8765 | Time: 0.56s
Batch 19/24 | Loss: 3.9520 | Time: 0.56s
Batch 20/24 | Loss: 3.7497 | Time: 0.56s
Batch 21/24 | Loss: 3.8803 | Time: 0.55s
Batch 22/24 | Loss: 3.9100 | Time: 0.56s
Batch 23/24 | Loss: 3.8193 | Time: 0.56s
Batch 24/24 | Loss: 3.0506 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 4.0477
Validation Loss: 3.5443
Training Time  : 18.54 sec
Validation Time: 4.33 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 3/50 ================
Batch 01/24 | Loss: 3.6635 | Time: 0.58s
Batch 02/24 | Loss: 3.5887 | Time: 0.55s
Batch 03/24 | Loss: 3.6429 | Time: 0.55s
Batch 04/24 | Loss: 3.5488 | Time: 0.56s
Batch 05/24 | Loss: 3.7437 | Time: 0.56s
Batch 06/24 | Loss: 3.5854 | Time: 0.55s
Batch 07/24 | Loss: 3.3701 | Time: 0.56s
Batch 08/24 | Loss: 3.5149 | Time: 0.56s
Batch 09/24 | Loss: 3.3929 | Time: 0.56s
Batch 10/24 | Loss: 3.6214 | Time: 0.56s
Batch 11/24 | Loss: 3.4862 | Time: 0.57s
Batch 12/24 | Loss: 3.4072 | Time: 0.56s
Batch 13/24 | Loss: 3.2974 | Time: 0.55s
Batch 14/24 | Loss: 3.3605 | Time: 0.56s
Batch 15/24 | Loss: 3.3905 | Time: 0.57s
Batch 16/24 | Loss: 3.2890 | Time: 0.55s
Batch 17/24 | Loss: 3.1879 | Time: 0.56s
Batch 18/24 | Loss: 3.4573 | Time: 0.55s
Batch 19/24 | Loss: 3.3729 | Time: 0.56s
Batch 20/24 | Loss: 3.3666 | Time: 0.55s
Batch 21/24 | Loss: 3.2898 | Time: 0.56s
Batch 22/24 | Loss: 3.3354 | Time: 0.55s
Batch 23/24 | Loss: 3.3622 | Time: 0.56s
Batch 24/24 | Loss: 2.6110 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 3.4119
Validation Loss: 3.1833
Training Time  : 18.33 sec
Validation Time: 4.28 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 4/50 ================
Batch 01/24 | Loss: 3.0961 | Time: 0.59s
Batch 02/24 | Loss: 3.1185 | Time: 0.55s
Batch 03/24 | Loss: 2.9605 | Time: 0.56s
Batch 04/24 | Loss: 3.1242 | Time: 0.56s
Batch 05/24 | Loss: 2.8834 | Time: 0.56s
Batch 06/24 | Loss: 3.1944 | Time: 0.56s
Batch 07/24 | Loss: 3.0385 | Time: 0.56s
Batch 08/24 | Loss: 2.9769 | Time: 0.56s
Batch 09/24 | Loss: 3.0540 | Time: 0.57s
Batch 10/24 | Loss: 2.8923 | Time: 0.56s
Batch 11/24 | Loss: 2.9803 | Time: 0.56s
Batch 12/24 | Loss: 3.0635 | Time: 0.56s
Batch 13/24 | Loss: 2.9899 | Time: 0.56s
Batch 14/24 | Loss: 2.9239 | Time: 0.56s
Batch 15/24 | Loss: 2.8882 | Time: 0.55s
Batch 16/24 | Loss: 2.8976 | Time: 0.56s
Batch 17/24 | Loss: 2.8885 | Time: 0.55s
Batch 18/24 | Loss: 3.0138 | Time: 0.55s
Batch 19/24 | Loss: 3.0127 | Time: 0.56s
Batch 20/24 | Loss: 3.0186 | Time: 0.56s
Batch 21/24 | Loss: 3.1171 | Time: 0.56s
Batch 22/24 | Loss: 2.9402 | Time: 0.56s
Batch 23/24 | Loss: 2.7478 | Time: 0.56s
Batch 24/24 | Loss: 2.4352 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 2.9690
Validation Loss: 2.9724
Training Time  : 18.44 sec
Validation Time: 4.30 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 5/50 ================
Batch 01/24 | Loss: 2.8274 | Time: 0.62s
Batch 02/24 | Loss: 2.6803 | Time: 0.56s
Batch 03/24 | Loss: 2.7092 | Time: 0.57s
Batch 04/24 | Loss: 2.5992 | Time: 0.56s
Batch 05/24 | Loss: 2.7368 | Time: 0.56s
Batch 06/24 | Loss: 2.7632 | Time: 0.55s
Batch 07/24 | Loss: 2.7287 | Time: 0.56s
Batch 08/24 | Loss: 2.7437 | Time: 0.56s
Batch 09/24 | Loss: 2.6416 | Time: 0.56s
Batch 10/24 | Loss: 2.5547 | Time: 0.56s
Batch 11/24 | Loss: 2.5622 | Time: 0.56s
Batch 12/24 | Loss: 2.5888 | Time: 0.56s
Batch 13/24 | Loss: 2.6894 | Time: 0.56s
Batch 14/24 | Loss: 2.7418 | Time: 0.56s
Batch 15/24 | Loss: 2.5975 | Time: 0.56s
Batch 16/24 | Loss: 2.6704 | Time: 0.56s
Batch 17/24 | Loss: 2.8335 | Time: 0.55s
Batch 18/24 | Loss: 2.7208 | Time: 0.57s
Batch 19/24 | Loss: 2.7403 | Time: 0.56s
Batch 20/24 | Loss: 2.5662 | Time: 0.56s
Batch 21/24 | Loss: 2.5888 | Time: 0.56s
Batch 22/24 | Loss: 2.5983 | Time: 0.56s
Batch 23/24 | Loss: 2.6449 | Time: 0.57s
Batch 24/24 | Loss: 1.8827 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 2.6421
Validation Loss: 2.7752
Training Time  : 18.40 sec
Validation Time: 4.32 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 6/50 ================
Batch 01/24 | Loss: 2.4321 | Time: 0.60s
Batch 02/24 | Loss: 2.4096 | Time: 0.56s
Batch 03/24 | Loss: 2.4478 | Time: 0.55s
Batch 04/24 | Loss: 2.4409 | Time: 0.56s
Batch 05/24 | Loss: 2.4635 | Time: 0.55s
Batch 06/24 | Loss: 2.4837 | Time: 0.56s
Batch 07/24 | Loss: 2.5015 | Time: 0.56s
Batch 08/24 | Loss: 2.4437 | Time: 0.56s
Batch 09/24 | Loss: 2.5055 | Time: 0.56s
Batch 10/24 | Loss: 2.5550 | Time: 0.55s
Batch 11/24 | Loss: 2.5065 | Time: 0.56s
Batch 12/24 | Loss: 2.2599 | Time: 0.56s
Batch 13/24 | Loss: 2.4203 | Time: 0.56s
Batch 14/24 | Loss: 2.4921 | Time: 0.56s
Batch 15/24 | Loss: 2.4092 | Time: 0.55s
Batch 16/24 | Loss: 2.4118 | Time: 0.56s
Batch 17/24 | Loss: 2.4510 | Time: 0.56s
Batch 18/24 | Loss: 2.3951 | Time: 0.56s
Batch 19/24 | Loss: 2.3107 | Time: 0.56s
Batch 20/24 | Loss: 2.4198 | Time: 0.56s
Batch 21/24 | Loss: 2.3559 | Time: 0.55s
Batch 22/24 | Loss: 2.4343 | Time: 0.55s
Batch 23/24 | Loss: 2.2567 | Time: 0.56s
Batch 24/24 | Loss: 1.6133 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 2.3925
Validation Loss: 2.6267
Training Time  : 18.37 sec
Validation Time: 4.25 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 7/50 ================
Batch 01/24 | Loss: 2.2336 | Time: 0.59s
Batch 02/24 | Loss: 2.0926 | Time: 0.57s
Batch 03/24 | Loss: 2.2814 | Time: 0.56s
Batch 04/24 | Loss: 2.2777 | Time: 0.55s
Batch 05/24 | Loss: 2.3051 | Time: 0.56s
Batch 06/24 | Loss: 2.1600 | Time: 0.56s
Batch 07/24 | Loss: 2.1102 | Time: 0.55s
Batch 08/24 | Loss: 2.2893 | Time: 0.56s
Batch 09/24 | Loss: 2.3331 | Time: 0.56s
Batch 10/24 | Loss: 2.0509 | Time: 0.57s
Batch 11/24 | Loss: 2.1059 | Time: 0.56s
Batch 12/24 | Loss: 2.2390 | Time: 0.56s
Batch 13/24 | Loss: 2.2622 | Time: 0.56s
Batch 14/24 | Loss: 2.3113 | Time: 0.56s
Batch 15/24 | Loss: 2.2968 | Time: 0.56s
Batch 16/24 | Loss: 2.2089 | Time: 0.56s
Batch 17/24 | Loss: 2.2063 | Time: 0.55s
Batch 18/24 | Loss: 2.1918 | Time: 0.56s
Batch 19/24 | Loss: 2.0925 | Time: 0.56s
Batch 20/24 | Loss: 2.2199 | Time: 0.56s
Batch 21/24 | Loss: 2.2792 | Time: 0.56s
Batch 22/24 | Loss: 2.2159 | Time: 0.56s
Batch 23/24 | Loss: 2.1586 | Time: 0.56s
Batch 24/24 | Loss: 1.4938 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 2.1840
Validation Loss: 2.5380
Training Time  : 18.30 sec
Validation Time: 4.23 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 8/50 ================
Batch 01/24 | Loss: 2.0227 | Time: 0.61s
Batch 02/24 | Loss: 1.9795 | Time: 0.57s
Batch 03/24 | Loss: 2.0531 | Time: 0.56s
Batch 04/24 | Loss: 1.9243 | Time: 0.55s
Batch 05/24 | Loss: 1.9529 | Time: 0.56s
Batch 06/24 | Loss: 1.9067 | Time: 0.55s
Batch 07/24 | Loss: 2.0239 | Time: 0.56s
Batch 08/24 | Loss: 2.0637 | Time: 0.56s
Batch 09/24 | Loss: 2.1640 | Time: 0.56s
Batch 10/24 | Loss: 1.9918 | Time: 0.56s
Batch 11/24 | Loss: 1.9229 | Time: 0.56s
Batch 12/24 | Loss: 1.7777 | Time: 0.56s
Batch 13/24 | Loss: 1.9564 | Time: 0.56s
Batch 14/24 | Loss: 2.1694 | Time: 0.56s
Batch 15/24 | Loss: 1.8665 | Time: 0.56s
Batch 16/24 | Loss: 1.9831 | Time: 0.56s
Batch 17/24 | Loss: 1.8867 | Time: 0.56s
Batch 18/24 | Loss: 2.0322 | Time: 0.57s
Batch 19/24 | Loss: 2.0247 | Time: 0.56s
Batch 20/24 | Loss: 1.9086 | Time: 0.56s
Batch 21/24 | Loss: 2.1271 | Time: 0.55s
Batch 22/24 | Loss: 2.0538 | Time: 0.56s
Batch 23/24 | Loss: 2.0447 | Time: 0.56s
Batch 24/24 | Loss: 1.3725 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.9670
Validation Loss: 2.4506
Training Time  : 18.39 sec
Validation Time: 4.19 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 9/50 ================
Batch 01/24 | Loss: 1.7673 | Time: 0.58s
Batch 02/24 | Loss: 1.7719 | Time: 0.56s
Batch 03/24 | Loss: 1.7779 | Time: 0.56s
Batch 04/24 | Loss: 1.9783 | Time: 0.56s
Batch 05/24 | Loss: 1.7568 | Time: 0.56s
Batch 06/24 | Loss: 1.9230 | Time: 0.56s
Batch 07/24 | Loss: 1.8151 | Time: 0.55s
Batch 08/24 | Loss: 1.8588 | Time: 0.55s
Batch 09/24 | Loss: 1.9231 | Time: 0.57s
Batch 10/24 | Loss: 1.8884 | Time: 0.56s
Batch 11/24 | Loss: 1.8558 | Time: 0.56s
Batch 12/24 | Loss: 1.8443 | Time: 0.56s
Batch 13/24 | Loss: 1.6920 | Time: 0.55s
Batch 14/24 | Loss: 1.8117 | Time: 0.56s
Batch 15/24 | Loss: 1.8024 | Time: 0.56s
Batch 16/24 | Loss: 1.9486 | Time: 0.56s
Batch 17/24 | Loss: 1.7789 | Time: 0.56s
Batch 18/24 | Loss: 1.8139 | Time: 0.56s
Batch 19/24 | Loss: 1.9847 | Time: 0.56s
Batch 20/24 | Loss: 1.7285 | Time: 0.56s
Batch 21/24 | Loss: 1.9149 | Time: 0.56s
Batch 22/24 | Loss: 1.8921 | Time: 0.56s
Batch 23/24 | Loss: 1.9518 | Time: 0.55s
Batch 24/24 | Loss: 1.0949 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.8156
Validation Loss: 2.3787
Training Time  : 18.17 sec
Validation Time: 4.26 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 10/50 ================
Batch 01/24 | Loss: 1.7121 | Time: 0.58s
Batch 02/24 | Loss: 1.7615 | Time: 0.56s
Batch 03/24 | Loss: 1.6921 | Time: 0.56s
Batch 04/24 | Loss: 1.6727 | Time: 0.56s
Batch 05/24 | Loss: 1.5480 | Time: 0.55s
Batch 06/24 | Loss: 1.6495 | Time: 0.56s
Batch 07/24 | Loss: 1.6502 | Time: 0.55s
Batch 08/24 | Loss: 1.5835 | Time: 0.56s
Batch 09/24 | Loss: 1.7415 | Time: 0.56s
Batch 10/24 | Loss: 1.6493 | Time: 0.56s
Batch 11/24 | Loss: 1.6076 | Time: 0.56s
Batch 12/24 | Loss: 1.6364 | Time: 0.56s
Batch 13/24 | Loss: 1.8220 | Time: 0.56s
Batch 14/24 | Loss: 1.6122 | Time: 0.56s
Batch 15/24 | Loss: 1.6202 | Time: 0.56s
Batch 16/24 | Loss: 1.5934 | Time: 0.56s
Batch 17/24 | Loss: 1.7318 | Time: 0.56s
Batch 18/24 | Loss: 1.8523 | Time: 0.56s
Batch 19/24 | Loss: 1.7630 | Time: 0.56s
Batch 20/24 | Loss: 1.8193 | Time: 0.56s
Batch 21/24 | Loss: 1.5148 | Time: 0.55s
Batch 22/24 | Loss: 1.7909 | Time: 0.56s
Batch 23/24 | Loss: 1.7741 | Time: 0.57s
Batch 24/24 | Loss: 1.2758 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.6698
Validation Loss: 2.3529
Training Time  : 18.40 sec
Validation Time: 4.21 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 11/50 ================
Batch 01/24 | Loss: 1.5994 | Time: 0.60s
Batch 02/24 | Loss: 1.5887 | Time: 0.56s
Batch 03/24 | Loss: 1.5320 | Time: 0.57s
Batch 04/24 | Loss: 1.6709 | Time: 0.55s
Batch 05/24 | Loss: 1.6926 | Time: 0.56s
Batch 06/24 | Loss: 1.6453 | Time: 0.55s
Batch 07/24 | Loss: 1.6410 | Time: 0.56s
Batch 08/24 | Loss: 1.6597 | Time: 0.57s
Batch 09/24 | Loss: 1.5911 | Time: 0.56s
Batch 10/24 | Loss: 1.5194 | Time: 0.56s
Batch 11/24 | Loss: 1.5113 | Time: 0.56s
Batch 12/24 | Loss: 1.5149 | Time: 0.56s
Batch 13/24 | Loss: 1.5093 | Time: 0.56s
Batch 14/24 | Loss: 1.6159 | Time: 0.56s
Batch 15/24 | Loss: 1.5195 | Time: 0.56s
Batch 16/24 | Loss: 1.5329 | Time: 0.57s
Batch 17/24 | Loss: 1.5645 | Time: 0.56s
Batch 18/24 | Loss: 1.5507 | Time: 0.56s
Batch 19/24 | Loss: 1.5945 | Time: 0.56s
Batch 20/24 | Loss: 1.5672 | Time: 0.56s
Batch 21/24 | Loss: 1.5695 | Time: 0.56s
Batch 22/24 | Loss: 1.6102 | Time: 0.56s
Batch 23/24 | Loss: 1.5714 | Time: 0.56s
Batch 24/24 | Loss: 0.9722 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.5560
Validation Loss: 2.3405
Training Time  : 18.16 sec
Validation Time: 4.21 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 12/50 ================
Batch 01/24 | Loss: 1.3388 | Time: 0.60s
Batch 02/24 | Loss: 1.4509 | Time: 0.56s
Batch 03/24 | Loss: 1.4907 | Time: 0.55s
Batch 04/24 | Loss: 1.4759 | Time: 0.56s
Batch 05/24 | Loss: 1.4328 | Time: 0.56s
Batch 06/24 | Loss: 1.6886 | Time: 0.56s
Batch 07/24 | Loss: 1.5077 | Time: 0.56s
Batch 08/24 | Loss: 1.5879 | Time: 0.56s
Batch 09/24 | Loss: 1.4558 | Time: 0.56s
Batch 10/24 | Loss: 1.4681 | Time: 0.56s
Batch 11/24 | Loss: 1.5680 | Time: 0.56s
Batch 12/24 | Loss: 1.4672 | Time: 0.57s
Batch 13/24 | Loss: 1.4895 | Time: 0.56s
Batch 14/24 | Loss: 1.4724 | Time: 0.56s
Batch 15/24 | Loss: 1.3814 | Time: 0.56s
Batch 16/24 | Loss: 1.4308 | Time: 0.56s
Batch 17/24 | Loss: 1.4054 | Time: 0.56s
Batch 18/24 | Loss: 1.5337 | Time: 0.56s
Batch 19/24 | Loss: 1.2817 | Time: 0.56s
Batch 20/24 | Loss: 1.5127 | Time: 0.56s
Batch 21/24 | Loss: 1.6810 | Time: 0.56s
Batch 22/24 | Loss: 1.4018 | Time: 0.55s
Batch 23/24 | Loss: 1.5007 | Time: 0.56s
Batch 24/24 | Loss: 0.9735 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.4582
Validation Loss: 2.3198
Training Time  : 18.28 sec
Validation Time: 4.21 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 13/50 ================
Batch 01/24 | Loss: 1.4681 | Time: 0.59s
Batch 02/24 | Loss: 1.3363 | Time: 0.56s
Batch 03/24 | Loss: 1.3764 | Time: 0.56s
Batch 04/24 | Loss: 1.3203 | Time: 0.56s
Batch 05/24 | Loss: 1.3795 | Time: 0.56s
Batch 06/24 | Loss: 1.3369 | Time: 0.56s
Batch 07/24 | Loss: 1.3986 | Time: 0.56s
Batch 08/24 | Loss: 1.3491 | Time: 0.56s
Batch 09/24 | Loss: 1.3765 | Time: 0.56s
Batch 10/24 | Loss: 1.4055 | Time: 0.56s
Batch 11/24 | Loss: 1.3553 | Time: 0.56s
Batch 12/24 | Loss: 1.3206 | Time: 0.55s
Batch 13/24 | Loss: 1.3976 | Time: 0.55s
Batch 14/24 | Loss: 1.3840 | Time: 0.56s
Batch 15/24 | Loss: 1.4142 | Time: 0.56s
Batch 16/24 | Loss: 1.2942 | Time: 0.56s
Batch 17/24 | Loss: 1.4157 | Time: 0.56s
Batch 18/24 | Loss: 1.2294 | Time: 0.57s
Batch 19/24 | Loss: 1.3022 | Time: 0.57s
Batch 20/24 | Loss: 1.5290 | Time: 0.56s
Batch 21/24 | Loss: 1.3226 | Time: 0.56s
Batch 22/24 | Loss: 1.3446 | Time: 0.56s
Batch 23/24 | Loss: 1.4172 | Time: 0.55s
Batch 24/24 | Loss: 0.9110 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.3494
Validation Loss: 2.3011
Training Time  : 18.35 sec
Validation Time: 4.18 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 14/50 ================
Batch 01/24 | Loss: 1.3437 | Time: 0.57s
Batch 02/24 | Loss: 1.3102 | Time: 0.56s
Batch 03/24 | Loss: 1.3653 | Time: 0.56s
Batch 04/24 | Loss: 1.2731 | Time: 0.57s
Batch 05/24 | Loss: 1.2733 | Time: 0.56s
Batch 06/24 | Loss: 1.2356 | Time: 0.56s
Batch 07/24 | Loss: 1.3761 | Time: 0.56s
Batch 08/24 | Loss: 1.2650 | Time: 0.56s
Batch 09/24 | Loss: 1.3289 | Time: 0.55s
Batch 10/24 | Loss: 1.3471 | Time: 0.56s
Batch 11/24 | Loss: 1.1332 | Time: 0.56s
Batch 12/24 | Loss: 1.2662 | Time: 0.56s
Batch 13/24 | Loss: 1.3137 | Time: 0.56s
Batch 14/24 | Loss: 1.1878 | Time: 0.56s
Batch 15/24 | Loss: 1.2820 | Time: 0.56s
Batch 16/24 | Loss: 1.2506 | Time: 0.56s
Batch 17/24 | Loss: 1.3305 | Time: 0.56s
Batch 18/24 | Loss: 1.3019 | Time: 0.56s
Batch 19/24 | Loss: 1.2905 | Time: 0.56s
Batch 20/24 | Loss: 1.3793 | Time: 0.56s
Batch 21/24 | Loss: 1.2704 | Time: 0.56s
Batch 22/24 | Loss: 1.2596 | Time: 0.56s
Batch 23/24 | Loss: 1.1923 | Time: 0.56s
Batch 24/24 | Loss: 0.9953 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.2738
Validation Loss: 2.2174
Training Time  : 18.27 sec
Validation Time: 4.28 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 15/50 ================
Batch 01/24 | Loss: 1.2238 | Time: 0.60s
Batch 02/24 | Loss: 1.2125 | Time: 0.56s
Batch 03/24 | Loss: 1.1873 | Time: 0.56s
Batch 04/24 | Loss: 1.1956 | Time: 0.56s
Batch 05/24 | Loss: 1.2424 | Time: 0.55s
Batch 06/24 | Loss: 1.1673 | Time: 0.56s
Batch 07/24 | Loss: 1.2015 | Time: 0.56s
Batch 08/24 | Loss: 1.1553 | Time: 0.56s
Batch 09/24 | Loss: 1.2298 | Time: 0.56s
Batch 10/24 | Loss: 0.9952 | Time: 0.56s
Batch 11/24 | Loss: 1.1189 | Time: 0.56s
Batch 12/24 | Loss: 1.1921 | Time: 0.56s
Batch 13/24 | Loss: 1.0872 | Time: 0.56s
Batch 14/24 | Loss: 1.1150 | Time: 0.56s
Batch 15/24 | Loss: 1.1855 | Time: 0.56s
Batch 16/24 | Loss: 1.2713 | Time: 0.56s
Batch 17/24 | Loss: 1.2095 | Time: 0.56s
Batch 18/24 | Loss: 1.1974 | Time: 0.56s
Batch 19/24 | Loss: 1.2316 | Time: 0.55s
Batch 20/24 | Loss: 1.1895 | Time: 0.56s
Batch 21/24 | Loss: 1.1672 | Time: 0.56s
Batch 22/24 | Loss: 1.1808 | Time: 0.56s
Batch 23/24 | Loss: 1.2580 | Time: 0.56s
Batch 24/24 | Loss: 0.7774 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.1663
Validation Loss: 2.2235
Training Time  : 18.37 sec
Validation Time: 4.24 sec
GPU Memory Used: 0.66 GB

================ Epoch 16/50 ================
Batch 01/24 | Loss: 1.1659 | Time: 0.56s
Batch 02/24 | Loss: 1.1147 | Time: 0.56s
Batch 03/24 | Loss: 0.9978 | Time: 0.56s
Batch 04/24 | Loss: 1.0519 | Time: 0.56s
Batch 05/24 | Loss: 1.1153 | Time: 0.56s
Batch 06/24 | Loss: 1.0580 | Time: 0.56s
Batch 07/24 | Loss: 1.0681 | Time: 0.56s
Batch 08/24 | Loss: 0.9553 | Time: 0.55s
Batch 09/24 | Loss: 1.0800 | Time: 0.56s
Batch 10/24 | Loss: 1.1073 | Time: 0.56s
Batch 11/24 | Loss: 1.1050 | Time: 0.56s
Batch 12/24 | Loss: 1.1408 | Time: 0.56s
Batch 13/24 | Loss: 1.1480 | Time: 0.56s
Batch 14/24 | Loss: 1.1753 | Time: 0.56s
Batch 15/24 | Loss: 1.1190 | Time: 0.56s
Batch 16/24 | Loss: 1.1582 | Time: 0.55s
Batch 17/24 | Loss: 1.1463 | Time: 0.56s
Batch 18/24 | Loss: 1.2283 | Time: 0.56s
Batch 19/24 | Loss: 1.1466 | Time: 0.55s
Batch 20/24 | Loss: 1.0932 | Time: 0.56s
Batch 21/24 | Loss: 1.0682 | Time: 0.57s
Batch 22/24 | Loss: 1.1377 | Time: 0.56s
Batch 23/24 | Loss: 1.1109 | Time: 0.56s
Batch 24/24 | Loss: 0.7943 | Time: 0.25s

---------------- Summary ----------------
Train Loss     : 1.0952
Validation Loss: 2.2020
Training Time  : 18.33 sec
Validation Time: 4.28 sec
GPU Memory Used: 0.66 GB
✓ Best model saved

================ Epoch 17/50 ================
Batch 01/24 | Loss: 1.0521 | Time: 0.58s
Batch 02/24 | Loss: 1.0775 | Time: 0.56s
Batch 03/24 | Loss: 0.9728 | Time: 0.56s
Batch 04/24 | Loss: 0.9627 | Time: 0.56s
Batch 05/24 | Loss: 1.0156 | Time: 0.56s
Batch 06/24 | Loss: 1.0630 | Time: 0.56s
Batch 07/24 | Loss: 0.9779 | Time: 0.56s
Batch 08/24 | Loss: 0.9507 | Time: 0.56s
Batch 09/24 | Loss: 1.0466 | Time: 0.56s
Batch 10/24 | Loss: 1.0094 | Time: 0.55s
Batch 11/24 | Loss: 1.1897 | Time: 0.55s

In [123]:
FINAL_MODEL_PATH = "/content/drive/MyDrive/MMRetrieval/ViT_Transformer_m1/best_retrieval_ViTTransformer_model.pth"

torch.save(model.state_dict(), BEST_MODEL_PATH)

Evaluation

In [124]:
def extract_embeddings(model, dataloader, device):
    model.load_state_dict(
    torch.load(FINAL_MODEL_PATH, map_location=device)
    )

    model.eval()


    image_embeddings = []
    text_embeddings = []

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            img_emb, txt_emb = model(images, captions, lengths)

            image_embeddings.append(img_emb.cpu())
            text_embeddings.append(txt_emb.cpu())

    image_embeddings = torch.cat(image_embeddings, dim=0)
    text_embeddings = torch.cat(text_embeddings, dim=0)

    return image_embeddings, text_embeddings

In [125]:
image_embs, text_embs = extract_embeddings(
    model,
    all_caption_test_loader,
    device
)

print(image_embs.shape)
print(text_embs.shape)

/tmp/ipykernel_10276/340369310.py:37: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return image, torch.tensor(caption)

torch.Size([5000, 512])
torch.Size([5000, 512])

In [126]:
# Similarity Matrix
unique_image_embs = image_embs[::5]

similarity = unique_image_embs @ text_embs.T

print("Image embeddings:", unique_image_embs.shape)
print("Text embeddings:", text_embs.shape)
print("Similarity:", similarity.shape)

Image embeddings: torch.Size([1000, 512])
Text embeddings: torch.Size([5000, 512])
Similarity: torch.Size([1000, 5000])

In [127]:
# image -> text
def image_to_text_recall(similarity, k):

    correct = 0

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        topk = similarity[img_idx].topk(k).indices.tolist()

        if any(idx in gt_caps for idx in topk):
            correct += 1

    return correct / similarity.shape[0]

In [128]:
def text_to_image_recall(similarity, k):

    similarity_t = similarity.T

    correct = 0

    for cap_idx in range(similarity_t.shape[0]):

        gt_img = cap_idx // 5

        topk = similarity_t[cap_idx]\
            .topk(k)\
            .indices\
            .tolist()

        if gt_img in topk:
            correct += 1

    return correct / similarity_t.shape[0]

In [129]:
def image_to_text_mrr(similarity):

    reciprocal_ranks = []

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        sorted_idx = torch.argsort(
            similarity[img_idx],
            descending=True
        )

        best_rank = float("inf")

        for cap in gt_caps:

            rank = (
                (sorted_idx == cap)
                .nonzero(as_tuple=True)[0]
                .item()
            ) + 1

            best_rank = min(best_rank, rank)

        reciprocal_ranks.append(
            1.0 / best_rank
        )

    return np.mean(reciprocal_ranks)

In [130]:
def text_to_image_mrr(similarity):

    similarity_t2i = similarity.T

    reciprocal_ranks = []

    for cap_idx in range(similarity_t2i.shape[0]):

        gt_image = cap_idx // 5

        sorted_idx = torch.argsort(
            similarity_t2i[cap_idx],
            descending=True
        )

        rank = (
            (sorted_idx == gt_image)
            .nonzero(as_tuple=True)[0]
            .item()
        ) + 1

        reciprocal_ranks.append(
            1.0 / rank
        )

    return np.mean(reciprocal_ranks)

In [131]:
results = pd.DataFrame({
    "Metric": [
        "Recall@1",
        "Recall@5",
        "Recall@10",
        "MRR"
    ],
    "Image→Text": [
        image_to_text_recall(similarity, 1),
        image_to_text_recall(similarity, 5),
        image_to_text_recall(similarity, 10),
        image_to_text_mrr(similarity)
    ],
    "Text→Image": [
        text_to_image_recall(similarity, 1),
        text_to_image_recall(similarity, 5),
        text_to_image_recall(similarity, 10),
        text_to_image_mrr(similarity)
    ]
})

results["Image→Text"] = results["Image→Text"].round(6)
results["Text→Image"] = results["Text→Image"].round(6)

display(results)

      Metric  Image→Text  Text→Image
0   Recall@1    0.297000    0.226600
1   Recall@5    0.589000    0.503000
2  Recall@10    0.704000    0.641400
3        MRR    0.431402    0.359915